server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.4:33016/vue?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

#mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  type-aliases-package: com/wen/pojo
