server:
  port: 8092


spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9987

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
#    hostname: 192.168.1.98
    preferIpAddress: true


##FeignClient超时设置
---
spring.cloud.loadbalancer.retry.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
ribbon.ConnectTimeout: 250
ribbon.ReadTimeout: 1000
ribbon.OkToRetryOnAllOperations: true
ribbon.MaxAutoRetriesNextServer: 2
ribbon.MaxAutoRetries: 1

---
#spring devtools 更改类程序文件不使用热部署自动重启
spring.devtools.restart.enabled: false
spring.devtools.livereload.enabled: false

fdfs:
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:
    width: 150
    height: 150
  trackerList:
    - 192.168.1.214:22122
    - 192.168.1.215:22122
spring.jmx.enabled: false

file.path.head: http://192.168.1.214:8080/

#security:
#  ignored: /favicon.ico,/scripts/**,/styles/**,/images/**,/webjars/**
#  sessions: ALWAYS
#  oauth2:
#      sso:
#        loginPath: /login
#      client:
#        clientId: ssoclient
#        clientSecret: ssosecret
#        accessTokenUri: http://localhost/oauth/token
#        userAuthorizationUri: http://localhost/oauth/authorize
#        clientAuthenticationScheme: form
#      resource:
#        jwt:
#          keyUri: http://localhost/oauth/token_key
#
#securityconfig:
#  logoutsuccssurl: /tosignout
#  permitall: /test/**,/hystrix**
#  deniedpage: /deny
#  #已使用数据库配置
#  urlroles: /**/new/** = admin;
#            /**/edit/** = admin,editor;
#            /**/delete/** = admin
