spring:
  application:
    name: eureka-server

server:
  port: 8761
  
eureka:
  client:
    fetch-registry: false #由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    register-with-eureka: false #由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己

