spring:
  application:
    name: CoderDreamMerchants
  datasource:
    url: jdbc:mysql://localhost:3306/passbook?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

server:
  port: 9527

logging:
  level:
    root: debug  # 指定日志基本
  file:
    name: coderdream-merchants.log  # 指定日志输出的文件路径
