apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    run: gateway-server
spec:
  ports:
    - name: port3
      protocol: TCP
      port: 8765
      nodePort: 30333
  selector:
    run: gateway-service
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    run: gateway-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: art.local:8081/docker/notebook-k8s/gateway-service:latest
        env:
          - name: NOTEBOOK_SERVICE
            value: "192.168.99.100"
          - name: CONFIG_SERVER_PORT
            value: "30222"
          - name: NOTEBOOK_SERVICE
            value: "192.168.99.100"
          - name: NOTEBOOK_SERVICE_PORT
            value: "30555"
          - name: ZIPKIN_SERVER
            value: "192.168.99.100"
          - name: ZIPKIN_SERVER_PORT
            value: "30411"
        ports:
        - containerPort: 8765
          protocol: TCP
      imagePullSecrets:
      - name: regcred-local
