spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://192.168.3.4:9411


#eureka:
#  client:
#    fetch-registry: false #由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
#    register-with-eureka: false #由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.4:8761/eureka/

server:
  port: 8765

zuul:
  routes:
    notebook:
      path: /**
      serviceId: notebook-service
    ribbon:
      eager-load:
        enabled: true
