spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://171.113.161.31:33016/real_time_data?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

# MybatisPlus配置
mybatis-plus:
  mapper-locations: classpath:com.coderdream.easyexcelpractise.mapper/*.xml