apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    run: zipkin-server
spec:
  ports:
  - name: port1
    protocol: TCP
    port: 9411
    nodePort: 30411
  selector:
    run: zipkin-service
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-service
  labels:
    run: zipkin-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: zipkin-service
    spec:
      containers:
      - name: zipkin-service
        image: openzipkin/zipkin
        env:
          - name: ZIPKIN_SERVER
            value: "192.168.99.100"
          - name: ZIPKIN_SERVER_PORT
            value: "9411"
        ports:
        - containerPort: 9411
          protocol: TCP
#TODO fix k8s